Fix query on unspecified property
cwida/duckpgq-extension pull request #191
Opened 2024-12-25 20:09 UTC by dentiny

Address issue https://github.com/cwida/duckpgq-extension/issues/190

The core idea for this PR is to get all columns in the property graph, and check whether the column to query is accessible or not.

2024-12-25 21:01 UTC, dentiny commented on src/core/functions/table/match.cpp
> +  CheckColumnBinding(*pg_table, *ref);
Having an additional validation function, instead of splitting and baking the validation logic into the multiple for loops seem to make code cleaner.

2025-01-09 10:40 UTC, Dtenwolde requested changes
Thank you for the PR! It's a good start to properly support the PROPERTIES functionality. I would like to see some more test cases that check if the correct columns are returned. 

A follow-up PR should also support the excluded column functionality that is tested here: https://github.com/cwida/duckpgq-extension/blob/5a584ebc59530be8622b69ec6a66fdc9e00a873f/test/sql/create_pg/except_properties.test. Then all columns should be returned except those listed. 

This might already be handled properly since we filter out these columns during the bind phase for every graph table: https://github.com/cwida/duckpgq-extension/blob/765d29f00978cab890015de565d638975aaee766/src/core/functions/table/create_property_graph.cpp#L57. Either way, we need to create test cases that handle these.

2025-01-09 10:40 UTC, Dtenwolde commented on src/core/functions/table/match.cpp
> +      col_names.insert(cur_col);
I'm wondering if this will also be sufficient for property graphs on attached databases. Then we also need to add the catalog and schema (`"catalog"."schema"."table"."column"`). 
I would like to see a test case handle this. For examples of attached databases, see https://github.com/cwida/duckpgq-extension/blob/9016214bbbbfd4e0f0fd5f4d9dfa74c61ab9d385/test/sql/create_pg/attach_pg.test

2025-01-09 10:40 UTC, Dtenwolde commented on src/core/functions/table/match.cpp
> +  CheckColumnBinding(*pg_table, *ref);
Agreed, thank you

2025-01-09 11:30 UTC, dentiny commented on src/core/functions/table/match.cpp
> +namespace {
The anonymous namespace (or `static`) is to constrain symbol to live only in the current translation unit.
Reference: https://google.github.io/styleguide/cppguide.html#Internal_Linkage

I don't have a strong preference for unamed namespace vs static; use the former here since it's used in my company.

2025-01-09 11:31 UTC, dentiny commented on src/core/functions/table/match.cpp
> +/*static*/ void
It's just a comment, which indicates current function is a static one, more for readability reason.

2025-01-09 11:33 UTC, dentiny commented
Thanks for the detailed review! TIL, I will try to get back before the end of this week.

2025-01-14 15:36 UTC, dentiny commented
I promise I will address these comments before the end of week.

2025-01-14 16:09 UTC, Dtenwolde commented
Hi @dentiny No worries, take your time. Next week I'll be busy with a conference anyway :)

2025-01-19 08:35 UTC, dentiny commented on src/core/functions/table/match.cpp
> +    if (column_ref == nullptr) {
I see what you mean; currently I don't see an easy solution.

I create another issue to track: https://github.com/cwida/duckpgq-extension/issues/198, and leave a TODO under my name.

2025-01-19 09:16 UTC, dentiny commented on src/core/functions/table/match.cpp
> +      col_names.insert(cur_col);
I think that's a good point, and it's not hard to get the catalog and schema name since they're already part of `PropertyGraphTable`.

However after some trials, I found it's failing due to another bind error:
https://github.com/cwida/duckdb-pgq/blob/4d5ca72d02b0844dc0acc6e605db5100b6761a29/src/planner/bind_context.cpp#L240-L255

Checking the variable, only `<table>.<column>` is stored in the `bindings` here.

2025-01-19 09:20 UTC, dentiny commented on src/core/functions/table/match.cpp
> +  D_ASSERT(sub_path != nullptr);
Yeah it's a sanity check, because we only have two possible types: path element and subpath.
As you mentioned, we already handled path element case above;
the check here is to make sure path reference is not unknown.
Let me know your preference, happy to change :)

2025-01-19 09:21 UTC, dentiny commented
I think most of the comments and responses are coding styles, let me know your preference, and I'm happy to change :)
Also left a TODO on handling non-column-ref expression case.

2025-01-24 10:38 UTC, Dtenwolde requested changes
Thanks for the updates, if we add a couple more test cases I think this PR is good to go :)

2025-01-24 10:38 UTC, Dtenwolde commented on src/core/functions/table/match.cpp
> +      col_names.insert(cur_col);
Alright, maybe we don't need the catalog and schema in that case. However, could you still add a test case to the attach_pg.test just to be sure?

2025-01-24 11:40 UTC, dentiny commented on src/core/functions/table/match.cpp
> +      col_names.insert(cur_col);
That makes sense; I added some more sql failure tests with catalog and schema prefix. Let me know if I understand correctly!

2025-01-25 12:49 UTC, Dtenwolde approved these changes
Thank you!

2025-01-25 12:51 UTC, merged